name: Prune GitHub Packages

on: workflow_dispatch

jobs:
  production:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Delete Package Versions
        uses: actions/delete-package-versions@v1.0.3
        with:
          package-name: "turbo-darwin-64"
          num-old-versions-to-delete: 3
      - name: Delete Package Versions
        uses: actions/delete-package-versions@v1.0.3
        with:
          package-name: "turbo-darwin-arm64"
          num-old-versions-to-delete: 3
      - name: Delete Package Versions
        uses: actions/delete-package-versions@v1.0.3
        with:
          package-name: "turbo-freebsd-64"
          num-old-versions-to-delete: 3
      - name: Delete Package Versions
        uses: actions/delete-package-versions@v1.0.3
        with:
          package-name: "turbo-freebsd-arm64"
          num-old-versions-to-delete: 3
      - name: Delete Package Versions
        uses: actions/delete-package-versions@v1.0.3
        with:
          package-name: "turbo-linux-32"
          num-old-versions-to-delete: 3
      - name: Delete Package Versions
        uses: actions/delete-package-versions@v1.0.3
        with:
          package-name: "turbo-linux-64"
          num-old-versions-to-delete: 3
      - name: Delete Package Versions
        uses: actions/delete-package-versions@v1.0.3
        with:
          package-name: "turbo-linux-arm"
          num-old-versions-to-delete: 3
      - name: Delete Package Versions
        uses: actions/delete-package-versions@v1.0.3
        with:
          package-name: "turbo-linux-arm64"
          num-old-versions-to-delete: 3
      - name: Delete Package Versions
        uses: actions/delete-package-versions@v1.0.3
        with:
          package-name: "turbo-linux-mips64le"
          num-old-versions-to-delete: 3
      - name: Delete Package Versions
        uses: actions/delete-package-versions@v1.0.3
        with:
          package-name: "turbo-linux-ppc64le"
          num-old-versions-to-delete: 3
      - name: Delete Package Versions
        uses: actions/delete-package-versions@v1.0.3
        with:
          package-name: "turbo-windows-32"
          num-old-versions-to-delete: 3
      - name: Delete Package Versions
        uses: actions/delete-package-versions@v1.0.3
        with:
          package-name: "turbo-windows-64"
          num-old-versions-to-delete: 3
